### ISSUE TITLE
Suggestion: Debug.LogError instead of Debug.Log when compilation finished with error

### ISSUE THREAD

**Issue by hsandt** [DarrenTsung/DTCompileTimeTracker#7]
I often glance at the bottom bar of Unity to check if an error occurred, so to me it would make sense to use Debug.LogError for the "Compilation Finished: Xs (error)" message so you can spot that an error occurred by seeing the red icon.

This should be easy to do, but I want to know what you think about it in terms of design (the message itself does not technically refers to a specific error, maybe a warning would be better?). Either way I'll create a fork of the project, but I'll only send a PR if you're interested.

**Comment by DarrenTsung** [comment]
Yeah, I agree that it being a Debug.LogError would make sense (if the error tracking was accurate).

But actually the way we check for errors is not that accurate :P. It basically scrapes the console for the count of error messages before and after compiling (more error messages after compiling == errors!). So that means in the case where code is being run on [InitializeOnLoad], OnValidate(), or other code paths that causes error messages will cause compile-time-tracker to believe there are compile errors, when there are not. Therefore, I didn't want it to appear as an actual error.
